### ISSUE TITLE
can't build project using cmake 

### ISSUE THREAD

**Issue by goodtogood** [AOT-AG/DicomToMesh#1]
win8.1 64bit VS2017

vtk D:\VTK-8.0.0
DicomToMesh D:\DicomToMesh

![cmake](https://user-images.githubusercontent.com/10088733/28487782-676e6826-6ecb-11e7-916f-316ae57c4579.png)

how to solve this problem? 
thanks!

**Comment by eidelen** [comment]
Hi,
Did you build VTK yourself? The cmake flag VTK_DIR has to point to the directory of your vtk build. In this directory, there is a file called VTKConfig.cmake.

**Comment by goodtogood** [comment]
It was built , but I set VTK_DIR to the source directory, my bad!
thank you so much!
