### ISSUE TITLE
Please can you make avalible in AUR for arch and manjaro users? 

### ISSUE THREAD

**Issue by brunachox** [AOT-AG/DicomToMesh#10]
I tried building it but error 2 apears

**Comment by eidelen** [comment]
Hi, I don't use arch nor manjaro. If somebody from this communities, you, would like put it there, feel free to do so. Of course I can help with building. What are the two building errors you receive?

**Comment by brunachox** [comment]
This two:
make[2]: *** No hay ninguna regla para construir el objetivo '/usr/lib/libnetcdf.so', necesario para 'lib/libdicom2meshlib.so'.  Alto.
make[1]: *** [CMakeFiles/Makefile2:91: lib/CMakeFiles/dicom2meshlib.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by eidelen** [comment]
Dicom2Mesh does not link _actively_ the netcdf library. Likely it is taken in over VTK. Could you build VTK?

**Comment by brunachox** [comment]
Yes, and sorry for not answer before, thank you very much

Atte. Bruno Frontini Ganem
El 9 de dic. de 2018 18:28 -0300, Adrian Schneider <notifications@github.com>, escribió:

Hi, I hope you could solve the building problems. As this issue is inactive for quite some time, I suggest that we close it. Do you agree?
