### ISSUE TITLE
How to use  DicomToMesh in server side

### ISSUE THREAD

**Issue by Chyper00** [AOT-AG/DicomToMesh#11]
Hii,
Im trying to build a project to manipulate a obj extracted from a dicom folder, so this will be a webapp , can i use DicomToMesh in a server side, to convert a dicoms files to a obj file for my app ? 
If this is possible can i get any help ? i really need. 
Thx

**Comment by eidelen** [comment]
Hi Diego,
You are allowed to use or modify DicomToMesh as you wish. However, there is no warranty from our side that the code is working correct.
If you are working with an Ubuntu server, you might be able to directly install Dicom2Mesh. Please see  https://github.com/AOT-AG/DicomToMesh#installation If you are working with an other platform you need to build it yourself https://github.com/AOT-AG/DicomToMesh#building

**Comment by Chyper00** [comment]
I see , there is away to deploy a build DicomToMesh in a host service like Firebase for exemple ? or works only in desktop ? 

Many thanks

**Comment by eidelen** [comment]
Hi Diego,
Sorry for my late answer. I am not familiar with Firebase. DicomToMesh does not need a desktop environment. But it requires pretty much RAM - depending on your DICOM, memory consumption can go up to 16 GB.

**Comment by eidelen** [comment]
Hi Diego! Is it fine for you when I close this issue?

**Comment by Chyper00** [comment]
yes, thanks
