### ISSUE TITLE
vtkMarchingCubes: Cannot contour data of dimension != 3

### ISSUE THREAD

**Issue by b5686109** [AOT-AG/DicomToMesh#13]
I'm trying to process tomography of some guy's leg into editable stl model.
Here's what I got:
```
$ dicom2mesh -i ~/DICOM/ST00001/SE00001 -o leg.stl

Dicom2Mesh Settings
-------------------
Input directory: /home/username/DICOM/ST00001/SE00001
Output file path: leg.stl
Surface segmentation: 400
Mesh reduction: disabled
Mesh polygon limitation: disabled
Mesh smoothing: disabled
Mesh centering: disabled
Mesh filtering: disabled
Volume cropping: disabled

Read DICOM images located under /home/username/DICOM/ST00001/SE00001
Progress: done

Create surface mesh with iso value = 400
Progress: 0.0%ERROR: In /tmp/portage/sci-libs/vtk-8.1.0-r2/work/VTK-8.1.0/Filters/Core/vtkMarchingCubes.cxx, line 417
vtkMarchingCubes (0x55793316cdc0): Cannot contour data of dimension != 3

Progress: done

No mesh could be created. Wrong DICOM or wrong iso value
```

1. I'm pretty sure that my DICOM file is not THAT wrong because dcm2pnm from DCMTK managed to extract layered images of leg from that DICOM file I've got. They look neat btw.
2. I'm not familiar with those DICOM or VTK things at all, so all I could do is just insert debug output for imageData->GetDataDimension() and it gave me 2.
3. Unfortunately, that DICOM file is about 700MB so it may be not a good idea to attach it here, though I can come up with something if it's not an obvious single-line bug but rather something that requires research.

**Comment by eidelen** [comment]
It is well possible that the standard vtk DICOM reader is not able to handle your DICOM format. For example, multiple series DICOM work neither.  
You have the possibility to build Dicom2Mesh with an extended DICOM format support. In the cmake, enable the flag `USE_VTK_DICOM`. The corresponding library can be cloned from https://github.com/dgobbi/vtk-dicom. This is mentioned in the readme file too.
Please let me know if that works. If it is fine for the leg owner, I can also look into the data :) Could you place them somewhere for downloading?

**Comment by eidelen** [comment]
Hi,
If it is still of interest to you, it might be good to build vtk-dicom with using gdcm. It is described [here](https://github.com/AOT-AG/DicomToMesh/issues/14#issuecomment-443224034).
