### ISSUE TITLE
Multithreading, is it possible?

### ISSUE THREAD

**Issue by cogitas3d** [AOT-AG/DicomToMesh#15]
Hey there!

I'm working with DicomToMesh on three OS (Linux, Mac OS X and Windows) and in all of them when I sent the DICOM to solve it uses only one thread.

I only realized this after I switched my PC to an i9 (9900k) and the time do not change a lot compared with an i7 (3770).

![Captura de tela de 2019-07-26 17-18-07](https://user-images.githubusercontent.com/2422483/61982031-70f67c80-afc9-11e9-96fa-1c2f6b84a37a.png)
Image: Only the CPU 2 worked to convert one DICOM to three STLs.

So, during the compilation, is it possible enable the  multithreading?
Thank you very much.

**Comment by eidelen** [comment]
Hi Cicero,
My observation is, that transforming the DICOM to a 3d mesh (vtkMarchingCubes) and also the reduction of this very mesh (vtkQuadricDecimation) are by far the most time consuming operations. I do not know these two algorithms in detail, but it is seems that they are not intended / implemented to run [in parallel](https://vtk.org/Wiki/VTK/Parallel#Algorithm-Level_.28threads.2C_MPI.2C_fine.29).
There might exist parallel alternatives to vtkQuadricDecimation and vtkMarchingCubes. If somebody is aware of such a substitute, please let us know. It would be great to speed up things.

**Comment by eidelen** [comment]
Hi Cicero,
From the CPU patterns, I have the feeling that I can observe the usage of several CPUs. I am using **VTK v.8.1.1**. Could you try with this version?

**Comment by cogitas3d** [comment]
Hi @eidelen !

I'm using VTK 6.3 on Linux 3DCS (Ubuntu 18.04).

I'm afraid to change the system library. Do you think it is possible?

A big hug!

**Comment by eidelen** [comment]
Hi Cicero,
I'm building VTK my self. It is not a big deal. But it is true, using the dedicated system version is the easiest path to go. Honestly, I understand little about that. 
When you build VTK yourself, you do not need to overwrite your system installation. Instead, in Dicom2Mesh cmake, you just point to your VTK 8.1.1 build directory. I can help you with that, if you want to give it a try.

**Comment by cogitas3d** [comment]
Great, I appreciate it. Thank you very much!

**Comment by eidelen** [comment]
Hi Cicero, I'm going to close this issue. Are you good with that?

**Comment by cogitas3d** [comment]
Hi @eidelen!

Perfect! Thank you!
