### ISSUE TITLE
Any utility to convert jpg image set to .dcm

### ISSUE THREAD

**Issue by shalinsirwani** [AOT-AG/DicomToMesh#16]
Actually i have exactly 100 images of an object with 3,60 degrees. Is there any way to convert these images to .DCM in order to use this tool???

**Comment by eidelen** [comment]
I do not understand what the "3,60 degrees" mean. In terms of converting jpg images to dicom images:
- There are the DCMTK command line tools. [This](https://support.dcmtk.org/docs/img2dcm.html) might be interesting for you.
- I found also another [tool](https://jpeg-to-dicom.en.softonic.com/) which is supposed to do the job. No idea if that works.

If you know C++, you could implement this feature directly into this tool, DicomToMesh. It should be straight forward, as the whole mesh creation is performed on vtkImageData. vtkImageData, on the other hand, can be generated from an image source, such as jpeg images. [Here](http://vtk.1045678.n5.nabble.com/Trying-to-read-a-set-of-jpg-slices-td5716283.html) is something similar. I can give you further information, if that would be an option for you. Would be a nice feature!

**Comment by shalinsirwani** [comment]
this type of error is generated. when i am processing DICOM file
No mesh could be created. Wrong DICOM or wrong iso value

**Comment by eidelen** [comment]
You might need to align the orientation of the images first. 
About the sample data: I do not have anything I am allowed to share.

**Comment by shalinsirwani** [comment]
### **"You might need to align the orientation of the images first"**
Whats wrong with these files : 
This is .dcm files for processing.  :- https://github.com/shalinsirwani/dcmfiles

**Comment by eidelen** [comment]
I don't what those files are and how you created them. There are known issues that compressed DICOM images, multi-series images, etc. can not be imported. You can overcome that problem by using an extended DICOM importer, as described [here](https://github.com/AOT-AG/DicomToMesh/issues/14#issuecomment-443224034)

**Comment by shalinsirwani** [comment]
After correcting number problem and building this tool with "USE_VTK_DICOM = ON". Now when i am opening "https://github.com/shalinsirwani/dcmfiles" these files in itk-snap it says vector too long, if possible please provide any clue why this is happening....

**Comment by eidelen** [comment]
Unfortunately, I do not know this error.

**Comment by eidelen** [comment]
Good morning, Is it fine when I am closing this issue or are you still working on it?

**Comment by shalinsirwani** [comment]
Hmm , I used this tool by passing .vti file directly to the marching cube. And that .vti file was generated by a tool named as Volview.
Nice tool !
