### ISSUE TITLE
PPA not exists on ubuntu 19.04

### ISSUE THREAD

**Issue by IgorDePaula** [AOT-AG/DicomToMesh#17]
PPA not exists on ubuntu 19.04
![Captura de tela de 2019-09-03 15-45-51](https://user-images.githubusercontent.com/2833993/64199993-f6d7d400-ce61-11e9-87e1-24fa12d98fd2.png)

**Comment by eidelen** [comment]
That's right. I added it just few minutes ago. Could you please try again and let me know if things are working?

**Comment by IgorDePaula** [comment]
Great. Now I can install normally. Thank you very much.
