### ISSUE TITLE
Wrong dicom error

### ISSUE THREAD

**Issue by IgorDePaula** [AOT-AG/DicomToMesh#18]
I try convert this dicom files https://www.dicomlibrary.com/?manage=1b9baeb16d2aeba13bed71045df1bc65 but the software says that file is wrong dicom.

![Captura de tela de 2019-09-04 10-56-53](https://user-images.githubusercontent.com/2833993/64261333-bbd9ad00-cf02-11e9-981e-57a707ed3869.png)

**Comment by eidelen** [comment]
These dicom files are compressed. With the dicom2mesh build from the ppa you cannot read compressed files. There are two ways:

- Building Dicom2Mesh yourself by considering following issue https://github.com/AOT-AG/DicomToMesh/issues/14#issuecomment-443224034
- Uncompress the files using tools, such as dcmtk

**Comment by IgorDePaula** [comment]
I got error on build vtk-dicom (https://github.com/AOT-AG/DicomToMesh/issues/14#issuecomment-443224034): 
```
By not providing "FindVTK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "VTK", but
  CMake did not find one.

  Could not find a package configuration file provided by "VTK" with any of
  the following names:

    VTKConfig.cmake
    vtk-config.cmake

  Add the installation prefix of "VTK" to CMAKE_PREFIX_PATH or set "VTK_DIR"
  to a directory containing one of the above files.  If "VTK" provides a
  separate development package or SDK, be sure it has been installed.

```

and I got install dcmtk but after install the system not recognize it, is like not are installed.

**Comment by IgorDePaula** [comment]
![Captura de tela de 2019-09-04 13-25-47](https://user-images.githubusercontent.com/2833993/64273377-8b503e00-cf17-11e9-89b0-006a73a7e013.png)
![Captura de tela de 2019-09-04 13-25-37](https://user-images.githubusercontent.com/2833993/64273378-8be8d480-cf17-11e9-8751-cf7f8a0b9b65.png)

**Comment by eidelen** [comment]
Good morning,
There is no binary named dcmtk. What you are interested in is the command **dcmjpeg**. This came with dcmtk on your system.
About the cmake error: You need to read the build instructions. In this case the VTK_DIR is not set. Please see [this](https://github.com/AOT-AG/DicomToMesh#building) and [that](https://github.com/AOT-AG/DicomToMesh/issues/1)

**Comment by IgorDePaula** [comment]
Waht I pretend is generate 3D object to render with javascript

**Comment by IgorDePaula** [comment]
Yes, VTK_DIR was setted, but I thing that VTK is not installed correctly.

![Captura de tela de 2019-09-05 09-36-00](https://user-images.githubusercontent.com/2833993/64342341-ad51cb00-cfc0-11e9-8765-b0226fcbb8da.png)

**Comment by drewp** [comment]
https://github.com/AOT-AG/DicomToMesh/issues/18#issuecomment-528225293 should say dcmdjpeg (not dcmjpeg). 

Before: 
```
dicom2mesh -i . -v

Read DICOM images located under .
ERROR: In /build/vtk7-d8SNZg/vtk7-7.1.1+dfsg1/IO/Image/vtkDICOMImageReader.cxx, line 105
vtkDICOMImageReader (0x55cb89114650): DICOMParser couldn't parse : ./conv

Progress: 0.0%ERROR: In /build/vtk7-d8SNZg/vtk7-7.1.1+dfsg1/IO/Image/vtkDICOMImageReader.cxx, line 333
vtkDICOMImageReader (0x55cb89114650): There was a problem retrieving data from: ./0196.dcm

ERROR: In /build/vtk7-d8SNZg/vtk7-7.1.1+dfsg1/Common/ExecutionModel/vtkExecutive.cxx, line 784
vtkCompositeDataPipeline (0x55cb891152f0): Algorithm vtkDICOMImageReader(0x55cb89114650) returned failure for request: vtkInformation (0x55cb89120710)
```

after:
```
apt install dcmtk
mkdir conv
for x (*.dcm)  { dcmdjpeg -v $x conv/$x }
cd conv
dicom2mesh -i . -v
(success)
```

**Comment by IgorDePaula** [comment]
I tried, but the generated images are not able to open.

**Comment by cogitas3d** [comment]
@IgorDePaula try to open the CT-Scan on Slicer, export it like a DICOM and try it again. Usually works.

**Comment by eidelen** [comment]
@IgorDePaula I am closing this issue. Feel free to reopen it. Thx, Adrian
