### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by bo-wu** [AOT-AG/DicomToMesh#19]
Hello authors,

Thanks for the excellent library with great features. I managed to compile the library with default configures as the following screenshot.

![Screenshot_2019-11-18_15-05-08](https://user-images.githubusercontent.com/8759514/69032194-df4ac900-0a16-11ea-8138-0d40565d572f.png)

However, when I tried to reconstruct mesh from a series dicom files, I got only "Segmentation fault" without any other info. I also tried command with mesh reduction and smooth, but still got same error. Would you please show me where I did wrong?

![Screenshot_2019-11-18_15-10-33](https://user-images.githubusercontent.com/8759514/69032213-eb368b00-0a16-11ea-9614-7a91e3166649.png)

Thanks in advances,

**Comment by eidelen** [comment]
Hi,
Sorry for the late reply. You mentioned that you wanted to open **a series dicom**.  Are there multiple datasets in the same directory? If that is the case, you need to enable USE_VTK_DICOM and get the corresponding library (it is mentioned in the readme). In anyway, USE_VTK_DICOM allows you to handle way more DICOM formats. Me personally, I prefer to use Dicom2Mesh with this option on.
Please let me know if that fixed your issue.

**Comment by bo-wu** [comment]
That's exactly my case. The problem is solved by the way you described. 
Thank you very much!

**Comment by eidelen** [comment]
Good to hear :-)

**Comment by bo-wu** [comment]
Hello Adrian @eidelen , 
I'm sorry to bother you again. I just have a puzzle and could not to figure it out: dose the reconstructed mesh has the same physical size (in mesh unit) with the ground truth?

if not, and I move the mass of mesh to the origin and scale the mesh according the dicom spacing parameters. Will this deform the mesh slightly and make it different from the ground truth?
Thanks in advance

**Comment by eidelen** [comment]
Hi,

Well I would not call it physical size. But in number they are the same, independent of the unit. For example, 2.5 mm and 2.5 inch are both 2.5 in mesh unit.

About the spacing: I’m pretty convinced that the dicom loader is considering the spacing and gets the necessary parameters (w, h, slice thickness…) from the dicom image. In this project, Dicom2Mesh, we did not observer such problems. However, if these parameters are wrong, the mesh will be deformed. 
Moving the mesh to the origin happens after creating mesh from the dicom. This step does not introduce any deformation. It is a pure linear transformation.. in fact only a translation.

Hope that helps you,
Adrian


Dr. Adrian Schneider
Seefeldstrasse 10, CH-3600 Thun

Tel: +41 79 592 49 65

adrian.schneider.pr@gmail.com

**Comment by bo-wu** [comment]
You're absolutely right. @eidelen 
Using the spacing parameters in dicom file can solve my puzzle.
Thank you very much!
