### ISSUE TITLE
Specific organs mesh

### ISSUE THREAD

**Issue by fedecere94** [AOT-AG/DicomToMesh#20]
I have a whole body series of CT scans.
With the command:  

> dicom2mesh -i pathToDicomDirectory -t isoValue -s -o mesh.stl 

I obtain the smoothed mesh.

Different iso-values correspond to different meshes (for example with -500 lungs and skin are visible, while with 100 or higher only bones are visible).

My problem is that I want to focus on specific organs (for example lungs) which are hidden by the skin, so to show them I have to zoom the obtained mesh until I pass the skin.
My questions is:
Is it possible to obtain only lungs mesh? Or more generally is it possible to eliminate the skin from the mesh, so as to make lungs easily visible in the mesh?

**Comment by eidelen** [comment]
With DicomToMesh, it is possible to apply an ISO value range. Coming back to your lung example: dicom2mesh -i pathToDicomDirectory **-t -500 -tu -50** -s -o mesh.stl
This generates a mesh from out all voxel with intensity -500 to -50. Of course, you have to play with the values. 
If this does not lead to any good result, I recommend you to have a look at ITK-Snap. This is a great tool to segment CT data!
