### ISSUE TITLE
Installation on ubuntu 18:04:repository not found

### ISSUE THREAD

**Issue by IgorDePaula** [AOT-AG/DicomToMesh#28]
![Captura de tela de 2020-08-31 11-08-35](https://user-images.githubusercontent.com/2833993/91729150-7e8e1680-eb7a-11ea-9953-6de957b22305.png)
![Captura de tela de 2020-08-31 11-09-33](https://user-images.githubusercontent.com/2833993/91729180-8948ab80-eb7a-11ea-9ab6-9e1331a5393b.png)

**Comment by eidelen** [comment]
Hi Igor,
I am on `Ubuntu 18.04.4 LTS` and I could just install from ppa. Could you please try again? Maybe the service was down.

```
$ sudo apt-get install dicom2mesh
Reading package lists... Done
Building dependency tree       
Reading state information... Done
...
After this operation, 1'567 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/eidelen/d2m/ubuntu bionic/main amd64 dicom2mesh amd64 0.8-0ppa0~bionic [195 kB]
Fetched 195 kB in 0s (573 kB/s)    
...
Unpacking dicom2mesh (0.8-0ppa0~bionic) ...
Setting up dicom2mesh (0.8-0ppa0~bionic) ...
```

**Comment by IgorDePaula** [comment]
![Captura de tela de 2020-09-02 10-41-44](https://user-images.githubusercontent.com/2833993/91991210-01dd7280-ed09-11ea-87d4-c31ebdc93b5d.png)
![Captura de tela de 2020-09-02 10-42-06](https://user-images.githubusercontent.com/2833993/91991226-04d86300-ed09-11ea-870e-ccbd68259a18.png)

**Comment by eidelen** [comment]
For me it is difficult to interpret your screenshots without any explanation. My guess is that it is somehow related to docker. Maybe [that](https://stackoverflow.com/questions/32486779/apt-add-repository-command-not-found-error-in-dockerfile) helps.

**Comment by IgorDePaula** [comment]
Now its install. Thank you very much.
