### ISSUE TITLE
ccmake not pointing to correct VTK directory

### ISSUE THREAD

**Issue by perthvr** [AOT-AG/DicomToMesh#4]
Hi thanks for your programme. I am having trouble getting ccmake to point to the correct VTK build directory. ( I did notice the file VTKConfig.cmake is located in both  home/sally/VTK-Release-build  and  home/sally/VTK-Release-build/CmakeFiles). This error could also be related to the setup of VTK as I had trouble getting it to talk to Qt5
                                                     
 This is my ccmake setup (note the missing USE_VTK_DICOM value)

CMAKE_BUILD_TYPE                 DEBUG                                        
 CMAKE_INSTALL_PREFIX             /usr/local                                   
 VTK_DIR                          /home/sally/VTK-Release-build 

   
and this is the ccmake error
 CMake Error at
 /home/sally/Downloads/vtk/VTK-8.1.0/CMake/vtkModuleAPI.cmake:143 (message):
   Requested modules not available:

     vtkMetaIO
     vtkjpeg
     vtkpng
     vtktiff
     vtkIOImage
     vtkImagingHybrid
     vtkInfovisLayout
     vtkImagingColor
     vtkRenderingAnnotation
     vtkRenderingVolume
     vtkInteractionWidgets
     vtkViewsCore
     vtklibproj4
     vtkGeovisCore

cheers and thanks Sally (newbie linux user)

**Comment by eidelen** [comment]
Hi,
DicomToMesh does not require to build VTK with Qt. 
If you built vtk in the directory /home/sally/VTK-Release-build, then your VTK_DIR is set correctly (in my case, VTK_DIR is where I called the command "make").

I notice that the path in the cmake error differs from your VTK_DIR:
- /home/sally/**Downloads**/vtk/VTK-8.1.0/
- /home/sally/VTK-Release-build
When you built VTK, did you call "make install" after building?

**Comment by perthvr** [comment]
Hi
 Yes I had not called make as I had got lost in the Qt  side of things during the installation of VTK. So I reinstalled VTK  without Qt and all is good
thanks for your help
