### ISSUE TITLE
Dicom2Mesh in action and acknowledgements

### ISSUE THREAD

**Issue by cogitas3d** [AOT-AG/DicomToMesh#5]
Hey there!

Our addon OrtogOnBlender now have Dicom2Mesh running with binaries in Linux and Windows.

You can see your sortware in action here: https://youtu.be/oxAOtztCYLM

Obs.: Our addon import and attach the skin to bone.

And the name of @eidelen in "Agradecimentos" (Acknowledgementes) here: https://github.com/cogitas3d/OrtogOnBlender

THANK YOU VERY MUCH this software is awesome!!!

**Comment by eidelen** [comment]
Thank you for the acknowledgment. Your work is very impressing! We are happy that you could make use of our software. Please have in mind that Dicom2Mesh could be rather easily translated into python, in as much as the main work is done by VTK.
