### ISSUE TITLE
How to select a serie description of CT-Scan?

### ISSUE THREAD

**Issue by cogitas3d** [AOT-AG/DicomToMesh#6]
Hey there!

The users having some troubles to convert CT-Scan to 3D using DicomToMesh, because they cannot select the DICOM Serie Description of tomographies.

For example, I opened the same CT-Scan in two different software:

![captura de tela de 2018-03-16 08-34-47](https://user-images.githubusercontent.com/2422483/37518665-7fa5dace-28ec-11e8-868e-5566cc9cf85d.png)
Above: InVesalius with HELICAL serie selected.

![captura de tela de 2018-03-16 08-35-39](https://user-images.githubusercontent.com/2422483/37518679-8de21314-28ec-11e8-836c-40d8650b63b3.png)
Above: Slicer 3D presenting the series on table.

I would like to know if its possible list and select the serie I want. And, a little more, if it's possible list the serie, list the number of slices and select that I want.

Thank you!

**Comment by eidelen** [comment]
Hi Cicero,
Nice to hear from you :) If you build with USE_VTK_DICOM=ON (please get https://github.com/dgobbi/vtk-dicom), Dicom2Mesh asks you which series to load, when there are more than one. It shows the number of slices too. Honestly, I did not test that carefully. Please let me know if it works.

**Comment by eidelen** [comment]
Hi Cicero, Did it finally work to use vtk-dicom to handle DICOMs with multiple series? If so, I suggest to close this issue.

**Comment by cogitas3d** [comment]
Hi @eidelen !

You're right.

I tryied to rebuild all, but like I have to make it run on three different SOs, I solved it in other way. I used Metadata DICOM information to create directories and separate the files:

https://www.facebook.com/ciceromoraes3d/videos/250023322380591/

The video is in Portuguese, but explain how it works.

Thank you again!
