### ISSUE TITLE
Instructions for Windows

### ISSUE THREAD

**Issue by UnderTheSun1** [AOT-AG/DicomToMesh#7]
Сould you give a short instruction about building on windows. What versions of msvc for dependencies, what version of Qt? Thank you for the product.

**Comment by eidelen** [comment]
On windows we are building dicom2mesh with
- Visual Studio 2015 
- VTK 7.0.0
The GUI can be optionally built. We use QT 5.9.4.

Please notice
(I) the guy is really experimental
(II) dicome2mesh likely works with all QT versions > 5 and VTK > 7

**Comment by UnderTheSun1** [comment]
Thank you so much!

**Comment by chenmiqin** [comment]
Сould you give a short instruction about building on windows.thanks!
