### ISSUE TITLE
Unable to build Dicom2Mesh on windows

### ISSUE THREAD

**Issue by Zulex** [AOT-AG/DicomToMesh#8]
Hello,

First of all, it really looks like great work and I highly appreciate it making it open source.

Unfortunately I'm not able to build DicomToMesh on windows. I Installed VTK 7.1.1 and one of the examples is working, so i'm assuming that part is okay.  Underneath you'll see how I'm using cmake(first time using cmake.). No errors or anything. I'm also starting visual studio manually as admin an my antivirus is turned off. But when building "ALL BUILD" I get the error in the second image. I saw in another issue someone having the same issue, but that should be fixed in a newer version. The version I have if from today. I'm also not sure if any other library will be missing after vtkmeshroutines.h since that is the first one.

Edit:
The other 2 libraries imported are also not reachable. See last picture.

Edit 2: Okay, It seems that when using git clone, this errors occur. Just downloading it as zip doesnt make any error pop up and cmake is showing options like the GUI, which didn't show on git clone files. But building the solution doesn't make a folder in program files (86x). The command "dicom2mesh" and "dicomtomesh" also don't work while visual studio is telling that the build succeeded without any errors. Using visual studio as admin and virusscanner is turned off.

Hope anyone can help me out:) Thanks in advance!   

<img width="438" alt="cmake1" src="https://user-images.githubusercontent.com/18424877/41301587-a9386d22-6e68-11e8-8c2c-487b23a6b00c.PNG">

<img width="972" alt="cmake2" src="https://user-images.githubusercontent.com/18424877/41301596-af465abc-6e68-11e8-800f-0ff546da47fe.PNG">

![image](https://user-images.githubusercontent.com/18424877/41302068-d6821732-6e69-11e8-9144-37fd180a0cab.png)

**Comment by eidelen** [comment]
Hi,
If those three header files cannot be found, the cmake configuration went wrong. This has nothing to do with git. I think I see what is the problem - you point to the wrong cmake file. Could you please try the following:
- In CMake, set the source code directory to C:/Users/....../DicomToMesh instead of  C:/Users/....../DicomToMesh/dicom2mesh

Basically, the "source code directory" is the location where the top CMakeLists.txt file is located. 
Hope it works, Adrian

**Comment by Zulex** [comment]
Hello,

It works for the cmake part and building without errors. But i'm still not seeing the folder created at  CMAKE_INSTALL_PREFIX location or any other. Starting visual studio as admin is not helping. 

For now using the pre-build files from another user I found in other issues seem to work correctly:). Maybe adding an prebuild windows version somewhere in the readme would help other windows users, since installing vtk can also be cumbersome. Thanks for the help!

**Comment by eidelen** [comment]
The cmake_install_prefix is only relevant if you call "make install". In your case when building worked, the binaries should be located under the build directory - something like C:/Users/....../Dicom2Mesh/build/dicom2mesh/Release/
and
C:/Users/....../Dicom2Mesh/build/lib/Release/
Easiest is to search the build directory for the files dicom2meshlib.dll and dicom2mesh.exe. To run the exe, the dll needs to be located in the same directory (or somewhere the PATH points to).

**Comment by Zulex** [comment]
@eidelen  Thanks! I got it working:)
