### ISSUE TITLE
Mesh must have normals and uvs

### ISSUE THREAD

**Issue by jst84** [AOT-AG/DicomToMesh#9]
Hi, I use this application to convert dicom files to obj file.
When I try to use it in a 3d application, something goes wrong with this message:
**"Mesh must have normals and uvs"**

Could you help me/there is any option that can I set on command line?

Thanks a lot,
Stefano.

**Comment by eidelen** [comment]
Hi Stefano,

Do you export the mesh as obj? Something like
> dicom2mesh -i xxx/yyy -o myMesh**.obj**

If that is the case, please try to export the mesh as stl
> dicom2mesh -i xxx/yyy -o myMesh**.stl**

We wrote the obj exporter ourself. It does not export uv coordinates. However, blender and meshlab are able to open our obj. What application do you use'

**Comment by jst84** [comment]
Hi eidelen, thanks for the quick response. 
Yes, I export the mesh as obj and then I use a custom software (something not famous) to view it.
I'm going to talk with the team about the stl format. 
Thanks a lot,
Stefano.

**Comment by eidelen** [comment]
Hi Stefano, 
Is this issue still active? If not, I suggest to close it. Fine for you? 
Thanks, Adrian

**Comment by jst84** [comment]
Hi Adrian,
yes, you do. I resolved by using a blender script that unwrap the mesh: bpy.ops.uv.cube_project().
Thanks a lot,
Stefano.
